spring:
  application:
    name: delivery

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_delivery
    username: postgres
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


ml_model: http://127.0.0.1:5000/predict